version: 2
registries:
  git-github-com:
    type: git
    url: https://github.com
    username: x-access-token
    password: "${{secrets.DEPENDABOT_ACCESS_TOKEN}}"

updates:
- package-ecosystem: composer
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  versioning-strategy: increase
  ignore:
  - dependency-name: laravel/framework
    versions:
    - "> 6.18.0, < 7"
  registries:
  - git-github-com
